name: "three-tier-depl"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform-Exec"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Apply Terraform Cofigurations
        id:   tf-execution
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
          # terraform destroy -auto-approve
